import Head from 'next/head';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { GetGreeter, SetGreeter } from '../components/contract';
import { Image } from '@chakra-ui/react';

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{ padding: '1rem' }}>
        {/* <ConnectButton /> */}
      </header>
      {/* <Image 
      alt='testing'
      // src='https://dweb.link/ipfs/bafybeidg2n55izufjix66osrvmwavjvajpq5mfou6lukze5cu32xdprfuq'
      src='https://bafybeidg2n55izufjix66osrvmwavjvajpq5mfou6lukze5cu32xdprfuq.ipfs.dweb.link/WSCryptoNerds-55.jpg'
      /> */}
      <main
        style={{
          minHeight: '60vh',
          flex: '1',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <GetGreeter />
        <SetGreeter />
      </main>
    </div>
  );
}
